# Generated by Django 2.2.5 on 2021-04-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_organizationmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Officecode', models.CharField(max_length=20)),
                ('officename', models.CharField(max_length=20)),
                ('attribution', models.CharField(max_length=20)),
            ],
        ),
    ]
