# Generated by Django 2.2.5 on 2021-04-05 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.CharField(max_length=20)),
                ('enddate', models.CharField(max_length=20)),
                ('officecode', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.Office')),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Subscriber')),
            ],
        ),
    ]
