# Generated by Django 2.2.5 on 2021-04-05 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferredSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferID', models.CharField(max_length=20)),
                ('transferfrom', models.CharField(max_length=20)),
                ('transferto', models.CharField(max_length=20)),
                ('requestdate', models.CharField(max_length=20)),
                ('transferdate', models.CharField(max_length=20)),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Subscriber')),
            ],
        ),
    ]
