# Generated by Django 2.2.5 on 2021-04-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubscriberID', models.CharField(max_length=20)),
                ('requestdate', models.CharField(max_length=20)),
                ('startdate', models.CharField(max_length=20)),
                ('enddate', models.CharField(max_length=20)),
                ('motifofcancellation', models.CharField(max_length=20)),
                ('BeneficiaryID', models.CharField(max_length=20)),
                ('servicecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Service')),
                ('subscriptiontypecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SubcriptionType')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Userinfo')),
            ],
        ),
    ]
